function [fitresult, gof] = Italy_fit(time, italy)
%CREATEFIT(TIME,ITALY)
%  Create a fit.
%
%  Data for 'Italy_Fit' fit:
%      X Input : time
%      Y Output: italy
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 25-Mar-2020 18:53:11


%% Fit: 'Italy_Fit'.
[xData, yData] = prepareCurveData( time, italy );

% Set up fittype and options.
ft = fittype( 'exp1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Algorithm = 'Levenberg-Marquardt';
opts.Display = 'Off';
opts.Normalize = 'on';
opts.Robust = 'LAR';
opts.StartPoint = [14.6118315670169 5.40706646572049];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'Italy_Fit' );
h = plot( fitresult, xData, yData );
legend( h, 'italy vs. time', 'Italy_Fit', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'time', 'Interpreter', 'none' );
ylabel( 'italy', 'Interpreter', 'none' );
grid on


